version: "3.9"

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: unless-stopped
    expose:
      - "5000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - flask_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
